import { useScrollReveal } from '../../hooks/useScrollReveal'

/* ── Mini preview colors (navy/gold theme generated by AI) ── */
const preview = {
  bg: '#0c1929',
  surface: '#132240',
  border: 'rgba(212,175,85,0.12)',
  accent: '#d4af55',
  accentSoft: 'rgba(212,175,85,0.08)',
  text: '#f0e8d8',
  text2: '#8a9ab8',
  text3: '#4a5a78',
}

function MiniCrmPreview() {
  return (
    <div
      className="rounded-xl overflow-hidden"
      style={{
        backgroundColor: preview.bg,
        border: `1px solid ${preview.border}`,
        boxShadow: '0 4px 24px rgba(0,0,0,0.3)',
      }}
    >
      {/* Mini top bar */}
      <div
        className="flex items-center justify-between px-3 py-2"
        style={{ borderBottom: `1px solid ${preview.border}` }}
      >
        <div className="flex items-center gap-2">
          <div
            className="w-5 h-5 rounded-md flex items-center justify-center text-[8px] font-bold"
            style={{ backgroundColor: preview.accent, color: preview.bg }}
          >
            A
          </div>
          <span className="text-[9px] font-semibold" style={{ color: preview.text }}>
            Apex Digital
          </span>
        </div>
        <div className="flex items-center gap-1.5">
          <div className="w-4 h-4 rounded-full" style={{ backgroundColor: preview.surface, border: `1px solid ${preview.border}` }} />
          <div
            className="w-5 h-5 rounded-full flex items-center justify-center text-[7px] font-bold text-white"
            style={{ backgroundColor: '#8a7a60' }}
          >
            JD
          </div>
        </div>
      </div>

      {/* Mini nav tabs */}
      <div
        className="flex items-center gap-3 px-3 py-1.5"
        style={{ borderBottom: `1px solid ${preview.border}` }}
      >
        {['Dashboard', 'Contacts', 'Pipeline'].map((tab, i) => (
          <span
            key={tab}
            className="text-[7px] pb-1"
            style={{
              color: i === 0 ? preview.accent : preview.text3,
              fontWeight: i === 0 ? 600 : 400,
              borderBottom: i === 0 ? `1.5px solid ${preview.accent}` : 'none',
            }}
          >
            {tab}
          </span>
        ))}
      </div>

      {/* Mini dashboard content */}
      <div className="p-3 space-y-2">
        {/* Stat row */}
        <div className="grid grid-cols-3 gap-2">
          {[
            { label: 'Contacts', value: '1,247' },
            { label: 'Deals', value: '38' },
            { label: 'Pipeline', value: '$127K' },
          ].map((stat) => (
            <div
              key={stat.label}
              className="rounded-lg p-2"
              style={{
                backgroundColor: preview.surface,
                border: `1px solid ${preview.border}`,
              }}
            >
              <p className="text-[6px] uppercase tracking-wider mb-0.5" style={{ color: preview.text3 }}>
                {stat.label}
              </p>
              <p className="text-[10px] font-bold" style={{ color: preview.text }}>
                {stat.value}
              </p>
            </div>
          ))}
        </div>

        {/* Mini chart area */}
        <div
          className="rounded-lg p-2"
          style={{
            backgroundColor: preview.surface,
            border: `1px solid ${preview.border}`,
          }}
        >
          <p className="text-[7px] font-semibold mb-1.5" style={{ color: preview.text }}>Revenue</p>
          <svg width="100%" viewBox="0 0 160 32" fill="none">
            <defs>
              <linearGradient id="ai-chart-fill" x1="0" y1="0" x2="0" y2="1">
                <stop offset="0%" stopColor={preview.accent} stopOpacity="0.2" />
                <stop offset="100%" stopColor={preview.accent} stopOpacity="0" />
              </linearGradient>
            </defs>
            <path
              d="M0,28 C20,24 30,18 50,20 C70,22 80,10 100,12 C120,14 130,6 160,4"
              stroke={preview.accent}
              strokeWidth="1.5"
              strokeLinecap="round"
            />
            <path
              d="M0,28 C20,24 30,18 50,20 C70,22 80,10 100,12 C120,14 130,6 160,4 L160,32 L0,32 Z"
              fill="url(#ai-chart-fill)"
            />
            <circle cx="160" cy="4" r="2.5" fill={preview.accent} opacity="0.6">
              <animate attributeName="r" values="2;4;2" dur="2s" repeatCount="indefinite" />
              <animate attributeName="opacity" values="0.6;0.2;0.6" dur="2s" repeatCount="indefinite" />
            </circle>
            <circle cx="160" cy="4" r="2" fill={preview.bg} stroke={preview.accent} strokeWidth="1" />
          </svg>
        </div>

        {/* Mini kanban */}
        <div className="grid grid-cols-3 gap-1.5">
          {[
            { title: 'Lead', color: '#16a34a', items: ['Sarah M.', 'Greenfield'] },
            { title: 'Qualified', color: '#3b82f6', items: ['Bright Path'] },
            { title: 'Proposal', color: preview.accent, items: ['Johnson Corp'] },
          ].map((col) => (
            <div key={col.title}>
              <div className="flex items-center gap-1 mb-1">
                <div className="w-1 h-1 rounded-full" style={{ backgroundColor: col.color }} />
                <span className="text-[6px] uppercase font-semibold tracking-wider" style={{ color: preview.text3 }}>
                  {col.title}
                </span>
              </div>
              {col.items.map((name) => (
                <div
                  key={name}
                  className="rounded p-1 mb-0.5"
                  style={{
                    backgroundColor: preview.bg,
                    border: `1px solid ${preview.border}`,
                    borderLeft: `2px solid ${col.color}`,
                  }}
                >
                  <span className="text-[6px]" style={{ color: preview.text2 }}>{name}</span>
                </div>
              ))}
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}

/* ── Typing cursor animation (CSS-in-JS) ── */
const cursorBlink = {
  animation: 'cursor-blink 1s steps(1) infinite',
}

export default function AiThemeGeneratorShowcase() {
  const { ref, isVisible } = useScrollReveal(0.1)

  return (
    <section className="relative py-24 sm:py-32 px-4 sm:px-6 overflow-hidden">
      {/* Inject cursor blink keyframes */}
      <style>{`
        @keyframes cursor-blink {
          0%, 100% { opacity: 1; }
          50% { opacity: 0; }
        }
      `}</style>

      {/* Background glow */}
      <div
        className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[900px] h-[500px] rounded-full opacity-8 blur-[140px]"
        style={{ background: 'radial-gradient(ellipse, #a855f7 0%, #5b8fff 40%, transparent 70%)' }}
      />

      <div
        ref={ref}
        className={`relative max-w-6xl mx-auto transition-all duration-700 ${
          isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'
        }`}
      >
        {/* Heading */}
        <div className="text-center mb-16">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-purple-500/20 bg-purple-500/5 backdrop-blur-md mb-6">
            <div
              className="w-4 h-4 rounded-md flex items-center justify-center"
              style={{ background: 'linear-gradient(135deg, #a855f7, #5b8fff)' }}
            >
              <svg width="8" height="8" viewBox="0 0 24 24" fill="none" stroke="white" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z" />
              </svg>
            </div>
            <span className="text-[11px] font-medium bg-gradient-to-r from-purple-400 to-blue-400 bg-clip-text text-transparent">
              AI-Powered
            </span>
          </div>

          <h2 className="text-4xl sm:text-5xl font-bold text-nestui-text mb-5 tracking-tight">
            Describe It. We'll Design It.
          </h2>
          <p className="text-nestui-text2 text-lg max-w-2xl mx-auto leading-relaxed">
            Tell our AI what your brand looks like and get a fully custom CRM theme in seconds.
            No design skills needed.
          </p>
        </div>

        {/* Two-column layout */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 lg:gap-10 items-center">
          {/* Left: Prompt input area */}
          <div className="relative">
            <div
              className="glass-card rounded-2xl p-6 sm:p-8 relative overflow-hidden"
              style={{
                boxShadow: '0 4px 24px rgba(0,0,0,0.15), 0 0 60px rgba(168,85,247,0.06)',
              }}
            >
              {/* Subtle gradient bg */}
              <div
                className="absolute inset-0 opacity-30 pointer-events-none"
                style={{
                  background: 'radial-gradient(ellipse at 20% 20%, rgba(168,85,247,0.08), transparent 60%)',
                }}
              />

              <div className="relative">
                {/* Label */}
                <div className="flex items-center gap-2 mb-4">
                  <div
                    className="w-6 h-6 rounded-lg flex items-center justify-center"
                    style={{ background: 'linear-gradient(135deg, #a855f7, #5b8fff)' }}
                  >
                    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                      <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z" />
                    </svg>
                  </div>
                  <span className="text-sm font-semibold text-nestui-text">Describe your brand</span>
                </div>

                {/* Fake text input */}
                <div
                  className="rounded-xl p-4 mb-4"
                  style={{
                    backgroundColor: 'rgba(255,255,255,0.03)',
                    border: '1px solid rgba(255,255,255,0.08)',
                    boxShadow: 'inset 0 1px 4px rgba(0,0,0,0.1)',
                  }}
                >
                  <p className="text-sm text-nestui-text2 leading-relaxed">
                    Modern agency with{' '}
                    <span className="text-nestui-text font-medium">navy blue</span>,{' '}
                    <span className="text-nestui-text font-medium">gold accents</span>, and a{' '}
                    <span className="text-nestui-text font-medium">clean minimal feel</span>.
                    Professional but warm — think luxury consulting firm.
                    <span
                      className="inline-block w-[2px] h-4 ml-0.5 align-middle bg-nestui-blue"
                      style={cursorBlink}
                    />
                  </p>
                </div>

                {/* Generate button */}
                <button
                  className="group w-full flex items-center justify-center gap-2 py-3 rounded-xl font-semibold text-sm text-white relative overflow-hidden transition-all duration-300 cursor-default"
                  style={{
                    background: 'linear-gradient(135deg, #a855f7, #5b8fff)',
                    boxShadow: '0 4px 20px rgba(168,85,247,0.3)',
                  }}
                >
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z" />
                  </svg>
                  Generate Theme
                </button>

                {/* Extracted colors */}
                <div className="mt-5 pt-4" style={{ borderTop: '1px solid rgba(255,255,255,0.06)' }}>
                  <p className="text-[10px] font-medium text-nestui-text3 uppercase tracking-widest mb-3">
                    Extracted palette
                  </p>
                  <div className="flex items-center gap-2">
                    {[
                      { color: '#0c1929', label: 'Background' },
                      { color: '#132240', label: 'Surface' },
                      { color: '#d4af55', label: 'Accent' },
                      { color: '#f0e8d8', label: 'Text' },
                      { color: '#8a9ab8', label: 'Secondary' },
                    ].map((swatch) => (
                      <div key={swatch.label} className="flex flex-col items-center gap-1 flex-1">
                        <div
                          className="w-full h-6 rounded-lg transition-transform duration-300 hover:scale-110"
                          style={{
                            backgroundColor: swatch.color,
                            border: '1px solid rgba(255,255,255,0.1)',
                            boxShadow: `0 2px 8px ${swatch.color}40`,
                          }}
                        />
                        <span className="text-[7px] text-nestui-text3">{swatch.label}</span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Right: Live preview */}
          <div className="relative">
            {/* Arrow connecting prompt to preview */}
            <div className="hidden lg:block absolute -left-8 top-1/2 -translate-y-1/2">
              <svg width="24" height="24" viewBox="0 0 24 24" fill="none" className="text-nestui-text3 opacity-40">
                <path d="M5 12h14M12 5l7 7-7 7" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
              </svg>
            </div>

            {/* Preview wrapper with glow */}
            <div className="relative">
              <div
                className="absolute -inset-4 rounded-3xl pointer-events-none"
                style={{
                  background: 'radial-gradient(ellipse at 50% 50%, rgba(212,175,85,0.08), transparent 70%)',
                  filter: 'blur(20px)',
                }}
              />

              {/* "Live Preview" badge */}
              <div className="flex items-center justify-between mb-3">
                <div className="flex items-center gap-2">
                  <span className="relative flex h-1.5 w-1.5">
                    <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-green-400 opacity-75" />
                    <span className="relative inline-flex h-1.5 w-1.5 rounded-full bg-green-400" />
                  </span>
                  <span className="text-[11px] font-medium text-nestui-text3">Live Preview</span>
                </div>
                <span className="text-[10px] px-2 py-0.5 rounded-md font-mono text-nestui-text3 bg-white/[0.04] border border-white/[0.06]">
                  navy-gold-minimal
                </span>
              </div>

              <MiniCrmPreview />
            </div>
          </div>
        </div>

        {/* Bottom note */}
        <p className="text-center mt-10 text-xs text-nestui-text3">
          Available on <span className="text-nestui-blue font-medium">Pro</span> and{' '}
          <span className="text-nestui-blue font-medium">Agency</span> plans
        </p>
      </div>
    </section>
  )
}
